<?php

namespace Database\Seeders;

use App\Models\Entidad;
use App\Models\User;
use Illuminate\Database\Seeder;

class EntidadesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        \DB::table('entidades')->delete();

        Entidad::create(['entidad'=>"VINAPE",'entidadtipo_id'=>'1','direccion'=>"Avinguda Marqués de l'Argentera 1, 1er 1a",'codpostal'=>'08003','localidad'=>"Barcelona",'provincia_id'=>'08','pais_id'=>'ES','nif'=>'B63407100','tfno'=>'675 926 580','emailgral'=>'xvives@vinape.com','emailadm'=>'xvives@vinape.com','web'=>'']);
        Entidad::create(['entidad'=>"SERVEIS D’ARQUITECTURA I ENGINYERIA AT3 OLLER-PEÑA S.L.P ",'entidadtipo_id'=>'1','direccion'=>"Gran de Gràcia 13, Pral. 1ª",'codpostal'=>'08012','localidad'=>"Barcelona",'provincia_id'=>'08','pais_id'=>'ES','nif'=>'B65544108','tfno'=>'','emailgral'=>'enricpc@telefonica.net','emailadm'=>'at3@at3.e.telefonica.net','web'=>'']);
        Entidad::create(['entidad'=>"NOMEN i ASSOCIATS, Arquitectes SLP",'entidadtipo_id'=>'1','direccion'=>"C/Provença 249, 1º 1ª",'codpostal'=>'08008','localidad'=>"Barcelona",'provincia_id'=>'08','pais_id'=>'ES','nif'=>'B63305569','tfno'=>'','emailgral'=>'','emailadm'=>'','web'=>'']);
        Entidad::create(['entidad'=>"ELIX REHABILITACION Y CONSTRUCCION S.L.",'entidadtipo_id'=>'1','direccion'=>"PASSATGE PERMANYER, 19",'codpostal'=>'08009','localidad'=>"Barcelona",'provincia_id'=>'08','pais_id'=>'ES','nif'=>'B65272924','tfno'=>'663791869','emailgral'=>'gregorio.fdelacuesta@elix.es','emailadm'=>'construccion@elix.es ','web'=>'www.elix.es']);
        Entidad::create(['entidad'=>"ELIX SCM PARTNERS, S.L.",'entidadtipo_id'=>'1','direccion'=>"PASSATGE PERMANYER, 19",'codpostal'=>'08009','localidad'=>"Barcelona",'provincia_id'=>'08','pais_id'=>'ES','nif'=>'B66961285','tfno'=>'663791869','emailgral'=>'gregorio.fdelacuesta@elix.es','emailadm'=>'construccion@elix.es ','web'=>'www.elix.es']);
        Entidad::create(['entidad'=>"TDA Arquitectura y Urbanismo 2002 SLP",'entidadtipo_id'=>'1','direccion'=>"C/Rambla Catalunya 89 Entlo 1ª",'codpostal'=>'08008','localidad'=>"Barcelona",'provincia_id'=>'08','pais_id'=>'ES','nif'=>'B35448125','tfno'=>'','emailgral'=>'','emailadm'=>'','web'=>'']);
        Entidad::create(['entidad'=>"B-CDBARQUITECTURA S.L.P.",'entidadtipo_id'=>'1','direccion'=>"C/Aragó 284, 2-2",'codpostal'=>'08007','localidad'=>"Barcelona",'provincia_id'=>'08','pais_id'=>'ES','nif'=>'B66730615','tfno'=>'661 371 513','emailgral'=>'cdb@cdbarquitectura.com','emailadm'=>'admin@cdbarquitectura.com ','web'=>'https://cdbarquitectura.com']);
        Entidad::create(['entidad'=>"PLASENCIA ARQUITECTURA SLP",'entidadtipo_id'=>'1','direccion'=>"MUNTANER 374, 1R 2A",'codpostal'=>'08006','localidad'=>"Barcelona",'provincia_id'=>'08','pais_id'=>'ES','nif'=>'B66096132','tfno'=>'607207191','emailgral'=>'adrianaplasencia@plasencia-arquitectura.com ','emailadm'=>'adrianaplasencia@plasencia-arquitectura.com ','web'=>'https://plasencia-arquitectura.com/']);
        Entidad::create(['entidad'=>"ALTIMA SERVEIS FUNERARIS S.L.",'entidadtipo_id'=>'1','direccion'=>"Avda. Gran Via 205",'codpostal'=>'08908','localidad'=>"L'Hospitalet de Llobregat",'provincia_id'=>'08','pais_id'=>'ES','nif'=>'B58387721','tfno'=>'616689424','emailgral'=>'JavierLamata@altima-sfi.com','emailadm'=>'facturas@altima-sfi.com ','web'=>'https://www.altima-sfi.com/']);
        Entidad::create(['entidad'=>"GESTIÓ INTEGRAL CEMENTIRIS NOMBER, S.L.",'entidadtipo_id'=>'1','direccion'=>"Carretera C‐1413a km 4,5",'codpostal'=>'08754','localidad'=>"El Papiol",'provincia_id'=>'08','pais_id'=>'ES','nif'=>'B59357707','tfno'=>'616689424','emailgral'=>'JavierLamata@altima-sfi.com','emailadm'=>'facturas@altima-sfi.com ','web'=>'https://www.altima-sfi.com/']);
        Entidad::create(['entidad'=>"ELYSIUS EUROPA S.L.",'entidadtipo_id'=>'1','direccion'=>"Carrer Saragossa, 6",'codpostal'=>'08830','localidad'=>"Sant Boi de Llobregat",'provincia_id'=>'08','pais_id'=>'ES','nif'=>'B 63230759','tfno'=>'616689424','emailgral'=>'JavierLamata@altima-sfi.com','emailadm'=>'facturas@altima-sfi.com ','web'=>'https://www.altima-sfi.com/']);
        Entidad::create(['entidad'=>"ALDABA OBRAS REUNIDAS S.L.",'entidadtipo_id'=>'1','direccion'=>"C/ Joaquim Castells, 9",'codpostal'=>'08980','localidad'=>"Sant Feliu de Llobregat",'provincia_id'=>'08','pais_id'=>'ES','nif'=>'B67452946','tfno'=>'616689424','emailgral'=>'JavierLamata@altima-sfi.com','emailadm'=>'facturas@altima-sfi.com ','web'=>'https://www.altima-sfi.com/']);
        Entidad::create(['entidad'=>"ESTEVE SITJA LÓPEZ (AUTÒNOM)",'entidadtipo_id'=>'1','direccion'=>"Carrer Folgueroles, 2 despatx‐3",'codpostal'=>'08022','localidad'=>"Barcelona",'provincia_id'=>'08','pais_id'=>'ES','nif'=>'35.038.068‐Y','tfno'=>'639333882','emailgral'=>'despatx@sitja.eu ','emailadm'=>'despatx@sitja.eu ','web'=>'']);
        Entidad::create(['entidad'=>"BARE 2005 S.L.",'entidadtipo_id'=>'1','direccion'=>"C/ El Masnou, 9",'codpostal'=>'08328','localidad'=>"Alella",'provincia_id'=>'08','pais_id'=>'ES','nif'=>'B‐63947089','tfno'=>'607954298','emailgral'=>'jos@bare.cat ','emailadm'=>'bare@bare.cat','web'=>'www.bare.cat']);
        Entidad::create(['entidad'=>"BARBER RENTERIA",'entidadtipo_id'=>'1','direccion'=>"C/ El Masnou, 9",'codpostal'=>'08328','localidad'=>"Alella",'provincia_id'=>'08','pais_id'=>'ES','nif'=>'B63947089','tfno'=>'607954298','emailgral'=>'jos@barber-renteria.com','emailadm'=>'br@barber-renteria.com ','web'=>'www.barber-renteria.com']);
        Entidad::create(['entidad'=>"PROMOCION IRV 2000,S.L.",'entidadtipo_id'=>'1','direccion'=>"C/Muntaner, 292 Entlo. 1ª",'codpostal'=>'08021','localidad'=>"Barcelona",'provincia_id'=>'08','pais_id'=>'ES','nif'=>'B‐62339031','tfno'=>'679 202 197','emailgral'=>'project@lapromo.es','emailadm'=>'project@lapromo.es','web'=>'www.lapromo.es']);
        Entidad::create(['entidad'=>"MIRIAM CAÑAMARES SÁNCHEZ (PARTICULAR)",'entidadtipo_id'=>'1','direccion'=>"Carrer Jovellanos, 67 2‐2",'codpostal'=>'08201','localidad'=>"Sabadell",'provincia_id'=>'08','pais_id'=>'ES','nif'=>'53341088V','tfno'=>'647075453','emailgral'=>'miriam.canyamares@gmail.com','emailadm'=>'miriam.canyamares@gmail.com','web'=>'']);
        Entidad::create(['entidad'=>"PGI TORRELLA S.L.",'entidadtipo_id'=>'1','direccion'=>"C/ IRENEU, 8 BAJOS",'codpostal'=>'08224','localidad'=>"Terrassa",'provincia_id'=>'08','pais_id'=>'ES','nif'=>'B66538323','tfno'=>'629219250','emailgral'=>'goretti.torrella@pgitorrella.com ','emailadm'=>'goretti.torrella@pgitorrella.com ','web'=>'http://www.pgitorrella.com/']);
        Entidad::create(['entidad'=>"ROSELLÓ SANGENÍS ARQUITECTES",'entidadtipo_id'=>'1','direccion'=>"Pl. de la Farga, 2,b1",'codpostal'=>'08014','localidad'=>"Barcelona",'provincia_id'=>'08','pais_id'=>'ES','nif'=>'','tfno'=>'646791928','emailgral'=>'msangenis@coac.net ','emailadm'=>'msangenis@coac.net ','web'=>'www.rosello-sangenis.com']);
        Entidad::create(['entidad'=>"ARQ 71 I ASSOCIATS SLP",'entidadtipo_id'=>'1','direccion'=>"CALLE L'AVENIR, 8 - BJ B",'codpostal'=>'08006','localidad'=>"Barcelona",'provincia_id'=>'08','pais_id'=>'ES','nif'=>'B63041974','tfno'=>'677417911','emailgral'=>'fbb@arq71.com ','emailadm'=>'fbb@arq71.com ','web'=>'http://arq71.com/?lang=es']);
        Entidad::create(['entidad'=>"MAS VALIENTE ARQUITECTOS S.L.P.",'entidadtipo_id'=>'1','direccion'=>"Sant Leopold 101, of.214",'codpostal'=>'08221','localidad'=>"Terrassa",'provincia_id'=>'08','pais_id'=>'ES','nif'=>'B65057218','tfno'=>'636494959','emailgral'=>'masvaliente@masvaliente.com','emailadm'=>'masvaliente@masvaliente.com','web'=>'www.masvaliente.com']);
        Entidad::create(['entidad'=>"ROMAN NOGUÉS CUSI",'entidadtipo_id'=>'1','direccion'=>"Avinguda Miranda, 3",'codpostal'=>'08950','localidad'=>"Esplgues",'provincia_id'=>'08','pais_id'=>'ES','nif'=>'35039243P','tfno'=>'609712250','emailgral'=>'rnc2504@gmail.com','emailadm'=>'rnc2504@gmail.com','web'=>'']);
        Entidad::create(['entidad'=>"JAIME GARNICA FERNANDEZ",'entidadtipo_id'=>'1','direccion'=>"Plaza Doctor Garriga, 2",'codpostal'=>'08173','localidad'=>"Sant Cugat del Vallès",'provincia_id'=>'08','pais_id'=>'ES','nif'=>'47655504X','tfno'=>'619615547','emailgral'=>'jaimegarnica@gmail.com','emailadm'=>'jaimegarnica@gmail.com','web'=>'']);
        Entidad::create(['entidad'=>"Marta Mulà Sicart (ADAPTEM)",'entidadtipo_id'=>'1','direccion'=>"Travessera de gràcia 329 2n 2a",'codpostal'=>'08025','localidad'=>"Barcelona",'provincia_id'=>'08','pais_id'=>'ES','nif'=>'46346432Y','tfno'=>'609 50 13 40 / 630 81 79 67/ 93 217 93 59','emailgral'=>'adaptem@adaptem.es','emailadm'=>'adaptem@adaptem.es','web'=>'']);
        Entidad::create(['entidad'=>"EUROCONSTRUC",'entidadtipo_id'=>'1','direccion'=>"",'codpostal'=>'','localidad'=>"",'provincia_id'=>'','pais_id'=>'ES','nif'=>'a','tfno'=>'','emailgral'=>'','emailadm'=>'','web'=>'']);
        Entidad::create(['entidad'=>"JOSÉ GARCIA PERPIÑÁ",'entidadtipo_id'=>'1','direccion'=>"Carrer Flors, 5, 5è 2a",'codpostal'=>'08001','localidad'=>"Barcelona",'provincia_id'=>'08','pais_id'=>'ES','nif'=>'51079986E','tfno'=>'639858670','emailgral'=>'josegperpina@gmail.com ','emailadm'=>'josegperpina@gmail.com ','web'=>'']);
        Entidad::create(['entidad'=>"NOVANTIA INTEGRAL SA",'entidadtipo_id'=>'1','direccion'=>"CALLE DIPUTACIO, 256 - P. 6 PTA. 2",'codpostal'=>'08007','localidad'=>"Barcelona",'provincia_id'=>'08','pais_id'=>'ES','nif'=>'A62119896','tfno'=>'680646839','emailgral'=>'luis.pascual@novantia.com ','emailadm'=>'luis.pascual@novantia.com ','web'=>'https://www.novantia.com/']);
        Entidad::create(['entidad'=>"COMUNIDAD DE BIENES CAN PUJOLET 17 (EUROCONSTRUC)",'entidadtipo_id'=>'1','direccion'=>"c/ Viladomat nº129 baixos",'codpostal'=>'08015','localidad'=>"Barcelona",'provincia_id'=>'08','pais_id'=>'ES','nif'=>'E-42819581','tfno'=>'93.218.75.95','emailgral'=>'lrubi@europrojectes.es','emailadm'=>'lrubi@europrojectes.es','web'=>'']);
        Entidad::create(['entidad'=>"NEREA VEGA GARCIA",'entidadtipo_id'=>'1','direccion'=>"C/Amadeu Torner 33-37, 3-3 ",'codpostal'=>'08902','localidad'=>"L'Hospitalet de Llobregat",'provincia_id'=>'08','pais_id'=>'ES','nif'=>'47871598L','tfno'=>'667918838','emailgral'=>'nereavega27@gmail.com','emailadm'=>'nereavega27@gmail.com','web'=>'']);
        Entidad::create(['entidad'=>"MARIA DOLORES GONZÁLEZ HERNÁNDEZ",'entidadtipo_id'=>'1','direccion'=>"C/Gran de Gràcia 13, 4t 2a",'codpostal'=>'08012','localidad'=>"Barcelona",'provincia_id'=>'08','pais_id'=>'ES','nif'=>'27900004S','tfno'=>'','emailgral'=>'','emailadm'=>'','web'=>'']);
        Entidad::create(['entidad'=>"GREG",'entidadtipo_id'=>'1','direccion'=>"C/ Moret 11",'codpostal'=>'','localidad'=>"Sant Cugat del Vallès",'provincia_id'=>'','pais_id'=>'ES','nif'=>'b','tfno'=>'659838526','emailgral'=>'','emailadm'=>'','web'=>'']);
        Entidad::create(['entidad'=>"AKTULAND 54 S.L.",'entidadtipo_id'=>'1','direccion'=>"Carrer Pl. Ausiàs March 1, 2do. 2da., ",'codpostal'=>'08195','localidad'=>"Sant Cugat del Vallès",'provincia_id'=>'08','pais_id'=>'ES','nif'=>'B-67112045','tfno'=>'607954298','emailgral'=>'jos@bare.cat ','emailadm'=>'bare@bare.cat','web'=>'www.bare.cat']);
        Entidad::create(['entidad'=>"Carles Duarte Majó",'entidadtipo_id'=>'1','direccion'=>"Prat de la Riba 85",'codpostal'=>'08232','localidad'=>"Viladecavalls",'provincia_id'=>'08','pais_id'=>'ES','nif'=>'46825571D','tfno'=>'661369229','emailgral'=>'cduartemajo@gmail.com','emailadm'=>'cduartemajo@gmail.com','web'=>'']);
        Entidad::create(['entidad'=>"Ajuntament d'Esplugues de Llobregat",'entidadtipo_id'=>'1','direccion'=>"Plaça Santa Magdalena, 5-6",'codpostal'=>'08950','localidad'=>"Esplugues de Llobregat",'provincia_id'=>'08','pais_id'=>'ES','nif'=>'P0807600B','tfno'=>'','emailgral'=>'csoriano@esplugues.cat','emailadm'=>'csoriano@esplugues.cat','web'=>'']);
        Entidad::create(['entidad'=>"MAJAVA DESIGN, SL",'entidadtipo_id'=>'1','direccion'=>"C/ Bacardi, 48 Local ",'codpostal'=>'08902','localidad'=>"Hospitalet de Llobregat",'provincia_id'=>'08','pais_id'=>'ES','nif'=>'B67542183','tfno'=>'931 09 20 82','emailgral'=>'juan@urba.barcelona / siyao@urba.barcelona','emailadm'=>'hui@urba.barcelona','web'=>'']);
        Entidad::create(['entidad'=>"ALOGIE PROYECTOS E INTERIORISMO SL",'entidadtipo_id'=>'1','direccion'=>"C/ Rambla Cataluña 52",'codpostal'=>'08007','localidad'=>"Barcelona",'provincia_id'=>'08','pais_id'=>'ES','nif'=>'B01867738','tfno'=>'','emailgral'=>'','emailadm'=>'','web'=>'']);
        Entidad::create(['entidad'=>"Marta Tonijoan Pujol",'entidadtipo_id'=>'1','direccion'=>"C/ Granollers, 47",'codpostal'=>'08173','localidad'=>" Sant Cugat del Vallés",'provincia_id'=>'08','pais_id'=>'ES','nif'=>'46235281Z','tfno'=>'','emailgral'=>'','emailadm'=>'','web'=>'']);
        Entidad::create(['entidad'=>"BARBA BARBA ASSOC., S.R.L",'entidadtipo_id'=>'1','direccion'=>"CMNO. ANTIC DE SANT JOAN 12. PLANTA 2, PUERTA 1",'codpostal'=>'08003 ','localidad'=>"Barcelona",'provincia_id'=>'08','pais_id'=>'ES','nif'=>'B01890649','tfno'=>'629893247','emailgral'=>'ramirodelia@gmail.com','emailadm'=>'ramirodelia@gmail.com','web'=>'']);
        Entidad::create(['entidad'=>"Sanchez-Piulachs SLP",'entidadtipo_id'=>'1','direccion'=>"Calle gran via de les Corts Catalanes, 523 - 3 1",'codpostal'=>'08011','localidad'=>"Barcelona",'provincia_id'=>'08','pais_id'=>'ES','nif'=>'B63046726','tfno'=>'652651342','emailgral'=>'apeguero@pbarquit.com','emailadm'=>'apeguero@pbarquit.com','web'=>'']);
        Entidad::create(['entidad'=>"FUNERARIA VILANOVA SA",'entidadtipo_id'=>'1','direccion'=>"c/ De La Masia Nova, S/n ",'codpostal'=>'08800','localidad'=>"Vilanova I La Geltrú",'provincia_id'=>'08','pais_id'=>'ES','nif'=>'A08839631','tfno'=>'616689424','emailgral'=>'JavierLamata@altima-sfi.com','emailadm'=>'facturas@altima-sfi.com ','web'=>'https://www.altima-sfi.com/']);
        Entidad::create(['entidad'=>"PROMONTORIA GALA PROPERTIES SL",'entidadtipo_id'=>'1','direccion'=>"CALLE PRINCIPE DE VERGARA, NUM. 112, PLANTA 4",'codpostal'=>'28002','localidad'=>"Madrid",'provincia_id'=>'28','pais_id'=>'ES','nif'=>'B88330345','tfno'=>'608 65 61 68','emailgral'=>'anna.santillana@arcadis.com','emailadm'=>'anna.santillana@arcadis.com','web'=>'']);
        Entidad::create(['entidad'=>"BREEZE INNOVACION ARQUITECTOS SLP",'entidadtipo_id'=>'1','direccion'=>"C/ Pare Miquel de Sarria Nº7 P2, 08034 Barcelona",'codpostal'=>'08034','localidad'=>"Barcelona",'provincia_id'=>'08','pais_id'=>'ES','nif'=>'B67620633','tfno'=>'933 397 372','emailgral'=>' abelanche@binarq.es','emailadm'=>' abelanche@binarq.es','web'=>'']);
        Entidad::create(['entidad'=>"COPCISA SA",'entidadtipo_id'=>'1','direccion'=>"CALLE CERVANTES, 55 - 08221 TERRASSA (Barcelona)",'codpostal'=>'08221','localidad'=>"Terrassa",'provincia_id'=>'08','pais_id'=>'ES','nif'=>'A08190696','tfno'=>'','emailgral'=>'','emailadm'=>'','web'=>'']);
        Entidad::create(['entidad'=>"Marta Ballés Muñoz",'entidadtipo_id'=>'1','direccion'=>"C/ Bartrina 217, CP:08226, Terrassa (Barcelona)",'codpostal'=>'08226','localidad'=>"Terrassa",'provincia_id'=>'08','pais_id'=>'ES','nif'=>'45985995W','tfno'=>'654234232','emailgral'=>'bartrina217@gmail.com','emailadm'=>'bartrina217@gmail.com','web'=>'']);
        Entidad::create(['entidad'=>"CONSULTURIA DE PROJECTES BARCELONA, SLP",'entidadtipo_id'=>'1','direccion'=>"C/ Carbonell 1",'codpostal'=>'08003','localidad'=>"Barcelona",'provincia_id'=>'08','pais_id'=>'ES','nif'=>'B64902745','tfno'=>'618730017','emailgral'=>'manel.garcia@pgiengineering.com','emailadm'=>'facturacio.cpbcn@pgiengineering.com','web'=>'www.pgiengineering.com']);
        Entidad::create(['entidad'=>"Marc Arnal Huguet ",'entidadtipo_id'=>'1','direccion'=>"Carrer Johann Sebastian Bach 9 baixos",'codpostal'=>'08021','localidad'=>"Barcelona",'provincia_id'=>'08','pais_id'=>'ES','nif'=>'38126499C','tfno'=>'','emailgral'=>'marnal.h@gmail.com','emailadm'=>'marnal.h@gmail.com','web'=>'']);
        Entidad::create(['entidad'=>"Piulachs-bellsolell Arquitectes S.l.p.",'entidadtipo_id'=>'1','direccion'=>"Calle gran via de les Corts Catalanes, 523 - P. 3, Barcelona, 08011 , Barcelona",'codpostal'=>'08011','localidad'=>"Barcelona",'provincia_id'=>'08','pais_id'=>'ES','nif'=>' B67359224','tfno'=>'93 454 78 98','emailgral'=>'dpiulachs@pbarquit.com','emailadm'=>'dpiulachs@pbarquit.com','web'=>'']);
    }
}
